name: Deployment project 
on: 
  push:
    branches: 
      - main 
      - "^release/v[0-9]+.[0-9]+$"

jobs: 
  dovbear: 

    if: "!startsWith(github.event.head_commit.message, '#NORUN')"
    runs-on: ubuntu-latest    
    steps: 

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
        
      - name: setup node.js env
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          

      - name: Display submission to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:  
          payload: |
            {
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "GdipSA 56 CICD Submission"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Name*: Tey Kee Yeow"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Email*: kee@u.nus.edu"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Matriculation*: A0112234Y"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Repository*:\n ${{ github.server_url }}/${{ github.repository }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "${{ secrets.RAILWAY_URL }}"
                    },
                    "accessory": {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "Go",
                        "emoji": true
                      },
                      "value": "click_me_123",
                      "url": "${{ secrets.RAILWAY_URL }}",
                      "action_id": "button-action"
                    }
                  }          
                ]
              }
      
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
